import type { SupportedLocale } from '@/i18n/appTranslations';

export type LegalDocumentId = 'terms' | 'privacy' | 'community' | 'deletion';

export type LegalSection = {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type LegalDocument = {
  id: LegalDocumentId;
  title: string;
  shortTitle: string;
  version: string;
  sections: LegalSection[];
};

const zhTW: Record<LegalDocumentId, LegalDocument> = {
  terms: {
    id: 'terms', title: 'GPulse 服務條款', shortTitle: '服務條款', version: '1.0 候選版', sections: [
      { heading: '一、接受條款', paragraphs: ['歡迎使用 GPulse。GPulse 為提供成年人建立個人檔案、探索其他使用者、互動、聊天、限時動態、私人相簿及其他社交功能之服務。', '建立帳號、登入或使用 GPulse，即表示您已閱讀並同意本服務條款、隱私權政策及社群規範；如不同意，請勿建立帳號或繼續使用服務。'] },
      { heading: '二、使用資格與帳號安全', paragraphs: ['GPulse 僅供年滿 18 歲之成年人使用。不得冒用他人、虛報年齡，或協助未成年人建立或使用帳號。若有合理理由認為帳號使用者未滿 18 歲，GPulse 得限制、暫停或終止帳號並採取必要安全措施。', '使用者應妥善保管帳號及登入憑證，不得出售、出租、轉讓帳號或讓他人冒用。發現未經授權登入或安全事件時，應儘速透過正式客服管道聯絡我們。GPulse 不會透過一般聊天訊息索取密碼。'] },
      { heading: '三、個人檔案、公開與私人內容', paragraphs: ['使用者得依現有功能提供名稱、年齡、自我介紹、所在地、身高、體重、族群、角色、尋找對象、公開照片及其他資料，並應確保內容具有合法權利且不侵害他人隱私、肖像、著作或其他權利。GPulse 無法保證其他使用者資料的真實性。', '公開檔案、公開照片及使用者主動設定公開的內容可能被符合條件的使用者看到。私人相簿原則上僅在擁有者核准後向特定使用者開放；它與公開照片採不同權限處理，且不得自動作為公開頭像或公開推薦照片。', '私人內容沒有絕對安全保障。獲准查看者仍可能以截圖、拍攝或其他裝置功能保存內容；請勿上傳無法承擔遭保存、轉傳或外流風險的內容。'] },
      { heading: '四、聊天、互動與禁止行為', paragraphs: ['使用者得依現有功能傳送訊息、按讚、申請私人相簿存取或進行其他互動。'], bullets: ['不得騷擾、威脅、跟蹤、恐嚇、詐騙、勒索、釣魚或冒用他人；', '不得散布未經當事人同意的私密影像，或傳送惡意程式、從事未經授權系統存取；', '不得大量傳送垃圾訊息，或從事其他違法、明顯危害使用者安全的行為。'] },
      { heading: '五、封鎖、限時動態與位置', paragraphs: ['GPulse 提供封鎖及其他安全控制。封鎖後，系統會依目前安全契約限制雙方可見性及部分互動；封鎖僅適用於 GPulse 服務內，無法控制平台外行為。', '限時動態為短期分享功能，依目前設計約於建立後 24 小時到期。使用者仍應確保內容具有合法使用與分享權利。', 'GPulse 僅在使用者主動啟用定位時要求裝置位置，不應僅因開啟個人檔案或隱私設定頁而自動要求定位。其他使用者看到的是概略距離區間（25 公里內、25 至 100 公里、100 公里以上），而非精確 GPS 座標。使用者可停止定位並清除本人位置資料。'] },
      { heading: '六、使用者內容、禁止內容與處置', paragraphs: ['使用者保有自行上傳內容原有權利；為提供、傳輸、顯示、儲存、維護及必要技術處理服務，使用者同意 GPulse 在必要範圍處理內容，這不代表 GPulse 取得內容所有權。GPulse 不得僅依本條款任意將私人相簿改為公開。'], bullets: ['禁止涉及未成年人的色情或性剝削、未經同意私密影像、威脅、暴力、嚴重騷擾或仇恨內容；', '禁止詐騙、冒用、勒索、惡意程式、釣魚、未經授權系統操作，以及明顯侵害他人著作、肖像或隱私權的內容。'], },
      { heading: '七、內容管理與服務變更', paragraphs: ['為維護安全、保護使用者、處理詐騙或濫用，或依法配合合法要求，GPulse 得依事件性質移除內容、限制功能、暫時限制或終止帳號，並應盡可能採取比例適當措施。', 'GPulse 仍在持續開發，可能新增、修改、限制或停止功能。重大權利或資料處理變更將依法提供必要通知。GPulse 將合理維護服務，但無法保證永不中斷、永久無錯誤或任何資料永久存在。'] },
      { heading: '八、VIP、互動風險與帳號刪除', paragraphs: ['介面可能展示 VIP 與未來規劃，但目前付款、正式訂閱、免費試用及付款後自動建立 VIP 資格的後端服務尚未正式啟用。單純進入或操作 VIP 介紹頁不會建立有效付費訂閱；付款上線前應另行提供價格、續訂、取消、退款及相關條件。', '使用者應自行判斷聊天、分享資訊或私人內容、及實際見面的風險。GPulse 無法保證使用者身分、資料、意圖或平台外行為，且不排除依法不得排除的法定權利。', '登出、停用及永久刪除不是同一操作。開發版本尚未完成安全永久帳號刪除後端；完成前介面不得偽稱已具備永久刪除能力，正式方式以《GPulse 帳號與資料刪除政策》為準。'] },
      { heading: '九、適用法律與聯絡', paragraphs: ['若 GPulse 最終由臺灣營運主體提供服務，本條款原則上依中華民國（臺灣）法律解釋及適用，但消費者保護、強制管轄及其他不可排除規定仍依相關法律處理。正式客服、營運主體及地址資訊將於正式上線前提供。'] },
    ],
  },
  privacy: {
    id: 'privacy', title: 'GPulse 隱私權政策', shortTitle: '隱私權政策', version: '1.0 候選版', sections: [
      { heading: '一、隱私原則', paragraphs: ['GPulse 是成年人社交與交友服務。個人檔案、照片、私人相簿、聊天、互動及位置相關資料可能高度私密；GPulse 依資料最小化、目的限制、權限分離及必要性原則處理資料。'] },
      { heading: '二、可能處理的資料', bullets: ['帳號與驗證資料：電子郵件、帳號識別碼及登入、驗證所需資訊。密碼由驗證系統安全處理，GPulse 不提供管理者或其他使用者查看明文密碼的功能。', '個人檔案：名稱、年齡、所在地或城市、自我介紹、族群、身高、體重、角色、尋找對象、公開照片及其他自願提供內容；部分資訊合併後可能揭露或推知高度敏感事項。', '公開照片：優先使用 public_photos 第一張，無則使用 avatar_url，再無則空白或預設視覺；私人照片絕不作為公開 fallback。', '私人相簿：與公開照片分離管理；未獲擁有者授權者不得透過正常應用程式流程讀取，且不會自動轉為公開頭像或推薦照片。', '聊天與互動：訊息、對話、時間、已讀狀態、按讚、封鎖、私人相簿申請與授權、通知及必要互動狀態。', '限時動態：內容、建立與到期時間、必要觀看狀態；有效動態目前約在建立後 24 小時到期。', '位置與距離：僅在主動操作位置功能後請求裝置位置；不向其他使用者直接顯示精確位置，而使用較粗略表示與距離區間。位置可更新或清除。'] },
      { heading: '三、處理目的', bullets: ['建立及維護帳號與個人檔案；提供探索、推薦、聊天、互動、私人相簿、限時動態與概略距離；', '執行封鎖與安全控制，防止濫用、詐騙及未經授權存取；提供客服、處理申訴、維護穩定與安全，並依法配合合法要求。'] },
      { heading: '四、目前未啟用或不得虛構的用途', paragraphs: ['開啟 VIP 頁不會自動建立付款或訂閱；GPulse 不會將私人相簿自動轉成公開照片、不向其他使用者直接顯示精確 GPS、也不應在單純開啟個人檔案或隱私頁時自動要求定位。', '目前尚未確認啟用第三方行為廣告或將使用者內容提供 AI 模型訓練。未來如新增 AI 處理、付款、第三方分析 SDK、廣告、推播供應商、錯誤追蹤或新用途，應在啟用前更新本政策並依法告知或取得必要同意。'] },
      { heading: '五、供應商、出售與跨境處理', paragraphs: ['已確認架構包含 Supabase 作為部分驗證、資料庫與後端服務；規劃使用 Vercel 作前端部署，正式發布前仍應以實際 Production 環境確認。發布前應核對實際供應商、目的、處理地區、保存與安全條款，且不得列入未使用供應商。', 'GPulse 不應出售個人資料；若未來有出售、交換或以資料取得對價的行為，應在實施前更新政策並依法處理。雲端基礎設施可能涉及跨境處理，GPulse 應依適用法律與實際供應商的保護機制處理，並在正式發布前確認區域。'] },
      { heading: '六、保存、安全與權利', paragraphs: ['資料僅在提供服務、維護安全、防制濫用、履行法律義務或處理合法爭議所必要期間保存。目的消失且無保存理由時，應停止使用、刪除或適當去識別化；發布前必須依 Production 架構完成保存期限 audit。', 'GPulse 採取合理技術措施，包括權限控制、資料存取限制、公開／私人資料分離、後端授權與安全控制，但任何網路服務均無法保證絕對安全。依法需通知之安全事件，將依適用法律處理與通知。', '依適用法律，使用者可能有查詢、閱覽、取得副本、更正、停止特定處理或請求刪除權利。權利內容依所在地與適用法律而定；發布前 GPulse 應提供明確行使管道。拒絕定位不應阻止與定位無關的主要功能，且使用者可清除位置資料。'] },
      { heading: '七、未成年人、變更與聯絡', paragraphs: ['GPulse 僅供 18 歲以上成年人使用。若合理確認未成年人帳號，可視情況限制、停止或刪除相關帳號與資料。', '若新增資料種類、改變目的、重要第三方、付款、廣告、AI 處理或重大保存方式，GPulse 應更新本政策並依法提供適當通知。正式隱私聯絡、客服、營運者與地址資訊將於正式上線前提供。'] },
    ],
  },
  community: {
    id: 'community', title: 'GPulse 社群規範', shortTitle: '社群規範', version: '1.0 候選版', sections: [
      { heading: '社群原則', paragraphs: ['GPulse 希望建立成年人能安全、尊重並自主互動的社群。'] },
      { heading: '一、僅限成年人與尊重同意', paragraphs: ['GPulse 僅供年滿 18 歲成年人使用。涉及未成年人之性內容、性剝削、引誘或要求交換私密內容皆禁止。', '任何性、情感、私人內容或社交互動都必須建立在同意上。其他使用者拒絕、停止回應或封鎖您時，應尊重其決定；不得持續騷擾、威脅或規避封鎖。'] },
      { heading: '二、禁止非自願私密影像、騷擾與仇恨', paragraphs: ['不得上傳、散布、公開、威脅散布或交換未經影像中當事人同意的私密照片或影片。'], bullets: ['不得威脅傷害、跟蹤、勒索、人肉搜尋、公開他人私人資料、持續騷擾、鼓吹暴力，或針對特定群體進行嚴重仇恨或貶抑。'] },
      { heading: '三、禁止冒用、詐騙與濫用自動化', bullets: ['不得冒用真實人物、團體或企業，或使用他人照片建立具有欺騙目的的身份。', '不得騙取匯款、進行投資或情感詐騙、竊取帳號、傳送釣魚網址、騙取密碼、驗證碼或其他高度敏感資料。', '不得大量重複傳送垃圾訊息，或使用未經允許的機器人、爬蟲、自動化工具干擾體驗、繞過限制或危害系統安全。'] },
      { heading: '四、內容權利、私人相簿與見面安全', paragraphs: ['只能上傳自行擁有或已取得合法授權的照片、影片及其他內容，不得明知侵害他人著作、肖像或其他合法權利。獲准觀看私人相簿不代表取得重製、公開、散布或轉傳的權利。', 'GPulse 無法確認每位使用者真實身分、背景或意圖。實際見面前請自行評估風險，避免過早提供住址、金融帳戶、身分證件、登入資訊、驗證碼或其他敏感資訊。'] },
      { heading: '五、封鎖、檢舉與違規處理', paragraphs: ['遇騷擾、安全問題、詐騙或不當行為時，應優先使用 GPulse 封鎖或檢舉功能；如有立即人身危險，請聯絡所在地緊急服務或執法機關。', '違反規範可能導致內容移除、功能限制、暫時限制帳號或永久停止帳號。重大安全事件或法律要求時，GPulse 得依法配合主管或執法機關。本規範可能依服務、安全風險及法律要求調整，重大變更將於適當位置通知。'] },
    ],
  },
  deletion: {
    id: 'deletion', title: 'GPulse 帳號與資料刪除政策', shortTitle: '帳號與資料刪除', version: '1.0 候選版', sections: [
      { heading: '一、帳號刪除與登出不同', paragraphs: ['使用者可以停止使用 GPulse，並在正式功能完成後要求永久刪除帳號。登出、暫時停用、關閉 App 或從裝置刪除 App 都不等於永久刪除帳號。'] },
      { heading: '二、目前開發版本狀態', paragraphs: ['GPulse 尚未完成能安全處理所有帳號關聯資料的永久帳號刪除後端。因此開發版本不得提供假的永久刪除成功訊息、將登出宣稱為刪除、僅刪除畫面資料卻保留後端帳號，或由前端直接執行未經完整資料生命週期設計的刪除。', '正式發布前，此功能必須完成獨立安全設計與驗證。'] },
      { heading: '三、未來刪除入口', paragraphs: ['正式版應提供容易找到的永久刪除入口，例如：個人 → 帳號設定 → 永久刪除帳號。最終介面與流程須在安全 backend 完成後再次驗證。', '若發布平台要求 App 外部入口，GPulse 應提供公開可存取的刪除網頁；目前正式網址尚未提供。'] },
      { heading: '四、預計範圍與聊天資料', paragraphs: ['正式流程原則上應評估並處理登入帳號、個人檔案、公開照片、私人相簿、位置、限時動態、私人相簿申請與授權、按讚與互動、通知、封鎖及其他直接綁定帳號資料。實際範圍必須依 Production schema、外鍵及安全需求進行正式 backend 設計。', '聊天資料可能涉及兩名以上使用者，前端不得自行猜測刪除方式。backend 實作前必須由人類核准策略，例如刪除寄件者內容、去識別化並保留對話完整性，或為安全、檢舉與法律義務保存必要內容。本文件不假裝未完成技術政策已經決定。'] },
      { heading: '五、必要保存與完成後效果', paragraphs: ['確有必要時，部分資料可能因防止詐騙或濫用、帳號及平台安全、法律義務、法院、主管或合法執法要求、爭議處理，或保護使用者與第三人權利而有限保存。不具保存必要性的資料仍應依流程移除或去識別化。', '正式流程成功後，帳號應無法再以原狀態登入，原檔案應停止作為有效使用者檔案公開顯示，核准範圍資料應依生命週期設計移除或去識別化；依法或因安全需要保留的有限資料則依隱私政策與法律處理。'] },
      { heading: '六、目前標示與正式發布 Gate', paragraphs: ['永久刪除帳號功能尚未完成安全後端流程，正式發布前將提供。除非後端確實完成所有必要操作，介面不得顯示「帳號已永久刪除」。'], bullets: ['正式發布前至少需完成 Production schema inventory、Auth 刪除設計、公開／私人照片、Story、Location、Notifications、Blocks／Likes 處理；', '需有人工核准的 Chat 與依法保存資料策略、安全 RPC 或受控 backend，以及完整 runtime 驗收。此 backend 工作不屬於本 Legal Center 階段。'] },
    ],
  },
};

const en: Record<LegalDocumentId, LegalDocument> = {
  terms: { id: 'terms', title: 'GPulse Terms of Service', shortTitle: 'Terms of Service', version: 'Version 1.0 Candidate', sections: [
    { heading: '1. Acceptance', paragraphs: ['Welcome to GPulse, a service for adults to create profiles, explore users, interact, chat, share Stories, use Private Album, and use other social features.', 'By creating an account, signing in, or using GPulse, you agree to these Terms, the Privacy Policy, and the Community Guidelines. If you disagree, do not create an account or continue using GPulse.'] },
    { heading: '2. Eligibility and account security', paragraphs: ['GPulse is only for adults aged 18 or older. Do not impersonate another person, misstate your age, or help a minor use GPulse. GPulse may restrict, suspend, or terminate an account if it reasonably believes the user is under 18.', 'Keep your credentials secure. Do not sell, rent, transfer, or let another person use your account. Report unauthorized sign-in through an official support channel. GPulse will not ask for your password in ordinary chat.'] },
    { heading: '3. Profiles, public content, and private content', paragraphs: ['Available features may let you provide your name, age, bio, location, height, weight, tribe, role, what you seek, public photos, and other profile information. You must have lawful rights to supplied content; GPulse cannot guarantee other users’ information is accurate.', 'Public profiles, public photos, and content you choose to make public may be visible to eligible users. Private Album is generally available to a specific person only after owner approval. It uses separate permissions and is never automatically used as a public avatar or recommendation photo.', 'Private content is not absolutely secure. An authorized viewer may save it by screenshot, camera, or other device features. Do not upload content if you cannot accept that risk.'] },
    { heading: '4. Interaction and prohibited conduct', bullets: ['Do not harass, threaten, stalk, intimidate, scam, extort, phish, or impersonate others.', 'Do not distribute non-consensual intimate imagery, send malware, access systems without authorization, send bulk spam, or conduct unlawful activity that clearly endangers users.'] },
    { heading: '5. Blocks, Stories, and location', paragraphs: ['GPulse provides blocking and safety controls. A block restricts mutual visibility and certain interactions under the current safety contract, but cannot control conduct outside GPulse.', 'Stories are short-term sharing features and currently expire about 24 hours after creation. You remain responsible for holding lawful rights to Story content.', 'Location is requested only after you actively enable it. Other users receive coarse distance buckets—within 25 km, 25–100 km, or more than 100 km—not exact GPS coordinates. You can stop location use and clear your location data.'] },
    { heading: '6. Content rights, moderation, and availability', paragraphs: ['You retain rights you originally have in uploaded content. You permit the processing needed to provide, transmit, display, store, maintain, and technically operate GPulse; this does not transfer ownership or allow GPulse to arbitrarily convert Private Album content to public content.', 'Prohibited content includes sexual or exploitative material involving minors, non-consensual intimate imagery, threats, violence, serious harassment or hate, scams, malware, phishing, unauthorized operations, and clear infringement. GPulse may remove content, limit features, restrict, or terminate accounts proportionately to protect safety or comply with law.', 'GPulse remains in development and may add, change, limit, or stop features. It will reasonably maintain the service but cannot guarantee uninterrupted, error-free, or permanent availability.'] },
    { heading: '7. VIP, interaction risk, and deletion', paragraphs: ['VIP interfaces and future plans may be shown, but payment, formal subscriptions, free trials, and backend VIP entitlement after payment are not formally enabled. Opening a VIP page does not create a paid subscription.', 'Assess the risks of chat, sharing information or private content, and meeting users. GPulse cannot guarantee identity, information, intent, or off-platform conduct, and does not exclude mandatory legal rights.', 'Sign-out, deactivation, and permanent deletion are different. The development version has no safe permanent account-deletion backend, so the interface must not claim deletion is available. See the Account & Data Deletion Policy.'] },
    { heading: '8. Law and contact', paragraphs: ['If GPulse is ultimately offered by a Taiwan operating entity, these Terms are generally interpreted under the laws of the Republic of China (Taiwan), subject to mandatory consumer and other non-excludable rules. Official support, operator, and address details will be provided before official launch.'] },
  ] },
  privacy: { id: 'privacy', title: 'GPulse Privacy Policy', shortTitle: 'Privacy Policy', version: 'Version 1.0 Candidate', sections: [
    { heading: '1. Privacy principles', paragraphs: ['GPulse is an adults-only social and dating service. Profiles, photos, Private Album, chat, interactions, and location-related data can be highly private. GPulse handles data under data-minimization, purpose-limitation, separation-of-permissions, and necessity principles.'] },
    { heading: '2. Data we may process', bullets: ['Account and verification data: email, account identifier, and information needed for sign-in and verification. Passwords are securely handled by the authentication system; GPulse provides no function for administrators or users to view plaintext passwords.', 'Profile data: name, age, location or city, bio, tribe, height, weight, role, what you seek, public photos, and voluntary content. Combined data may reveal or infer highly sensitive matters.', 'Public photos: the first public_photos item is used first, then avatar_url, then an empty/default visual. Private photos are never a public fallback.', 'Private Album: separately managed from public photos; unauthorized users cannot read it through normal app flows, and it is not automatically converted into a public avatar or recommendation photo.', 'Chat and interaction data: messages, conversations, times, read state, likes, blocks, Private Album requests/access, notifications, and required interaction state.', 'Stories: content, creation/expiry times, and necessary viewing state; an active Story currently expires about 24 hours after creation.', 'Location/distance: requested only after active user action; exact device location is not directly shown to users, while coarse distance buckets may be shown. Location can be updated or cleared.'] },
    { heading: '3. Purposes and uses not to be invented', paragraphs: ['GPulse may use necessary data to maintain accounts/profiles, provide Explore, recommendations, chat, interactions, Private Album, Stories, and coarse distance; operate safety controls; prevent fraud and unauthorized access; handle reports; maintain stability; and comply with lawful requests.', 'Opening a VIP page does not create payment or subscription. GPulse does not automatically convert Private Album into public photos, show exact GPS to other users, or request location merely because a profile/privacy page opens. Behavioral advertising and AI-model training with user content are not currently confirmed as enabled. Any future AI processing, payments, analytics SDKs, advertising, push providers, error tracking, or new use requires a policy update and required notice or consent before enablement.'] },
    { heading: '4. Providers, sale, cross-border processing, and retention', paragraphs: ['The confirmed architecture includes Supabase for parts of authentication, database, and backend services. GPulse plans Vercel for frontend deployment, subject to confirmation in the actual Production environment. Before launch, GPulse must verify actual providers, purposes, regions, retention, and protection terms, and must not list unused providers.', 'GPulse should not sell personal data. Any future sale, exchange, or data-for-value model requires a prior policy update and lawful handling. Cloud infrastructure may involve cross-border processing; GPulse must follow applicable law and actual provider protections.', 'Data is retained only as needed for service, safety, abuse prevention, legal obligations, or lawful disputes. When no retention reason remains, it should stop being used, be deleted, or be appropriately de-identified. Production retention needs an audit before launch.'] },
    { heading: '5. Security, rights, and changes', paragraphs: ['GPulse uses reasonable measures including access controls, access limits, public/private separation, backend authorization, and safety controls, but no service can guarantee absolute security. Incidents requiring notice will be handled under applicable law.', 'Depending on applicable law, you may have access, copy, correction, objection/stop-processing, and deletion rights. Refusing location should not prevent main features unrelated to location, and you may clear location through available controls.', 'GPulse is adults-only. If it reasonably confirms a minor account, it may restrict, stop, or delete the account/data. Material changes to data categories, purposes, providers, payment, advertising, AI processing, or retention require a policy update and appropriate notice. Official contact details will be provided before launch.'] },
  ] },
  community: { id: 'community', title: 'GPulse Community Guidelines', shortTitle: 'Community Guidelines', version: 'Version 1.0 Candidate', sections: [
    { heading: 'Community principle', paragraphs: ['GPulse aims to be a community where adults interact safely, respectfully, and autonomously.'] },
    { heading: '1. Adults, respect, and consent', paragraphs: ['GPulse is only for adults 18 and over. Sexual content, exploitation, grooming, or requests to exchange private content involving minors are prohibited.', 'Sexual, emotional, private-content, and social interaction must be based on consent. Respect a refusal, no response, or a block; do not harass, threaten, or evade blocking.'] },
    { heading: '2. Intimate imagery, harassment, and hate', paragraphs: ['Do not upload, distribute, publish, threaten to distribute, or exchange intimate imagery without the consent of the person depicted.'], bullets: ['Do not threaten harm, stalk, extort, dox, disclose private data, persistently harass, encourage violence, or seriously hate or demean a group.'] },
    { heading: '3. Impersonation, scams, spam, and automation', bullets: ['Do not impersonate people, groups, or businesses, or use another person’s photo for a deceptive identity.', 'Do not seek money, conduct investment/romance scams, steal accounts, send phishing links, or obtain passwords, verification codes, or sensitive data.', 'Do not send bulk repeated spam or use unauthorized bots, crawlers, or automation to disrupt users, bypass limits, or harm security.'] },
    { heading: '4. Content, Private Album, and meeting safety', paragraphs: ['Only upload content you own or have lawful permission to use. Approval to view Private Album does not grant a right to reproduce, publish, distribute, or forward it.', 'GPulse cannot verify every user’s identity, background, or intent. Before meeting, assess risks and avoid sharing address, financial account, ID documents, sign-in information, verification codes, or other highly sensitive information too early.'] },
    { heading: '5. Reports and enforcement', paragraphs: ['For harassment, safety problems, scams, or other misconduct, use blocking/reporting first. For immediate danger, contact local emergency services or law enforcement.', 'Violations may lead to removal, feature limits, temporary restriction, or permanent termination. GPulse may cooperate with lawful authority requests. Material guideline updates will be notified appropriately.'] },
  ] },
  deletion: { id: 'deletion', title: 'GPulse Account & Data Deletion Policy', shortTitle: 'Account & Data Deletion', version: 'Version 1.0 Candidate', sections: [
    { heading: '1. Deletion is different from sign-out', paragraphs: ['You may stop using GPulse and, once the formal feature is complete, request permanent deletion. Sign-out, temporary deactivation, closing the app, or removing it from a device do not permanently delete an account.'] },
    { heading: '2. Current development status', paragraphs: ['GPulse has not completed a permanent-account-deletion backend that safely handles all account-related data. The development version must not show fake deletion success, describe sign-out as deletion, remove only UI data while retaining the backend account, or perform deletion directly from the client without a full data-lifecycle design.', 'Independent security design and verification are required before release.'] },
    { heading: '3. Future entry points', paragraphs: ['A released version should make permanent deletion easy to find, for example Profile → Account settings → Permanently delete account. The final flow must be verified again after a safe backend exists. If a platform requires an external deletion page, GPulse should provide one; no official URL is available yet.'] },
    { heading: '4. Scope and chat', paragraphs: ['A formal flow should assess and handle directly related Auth account, profile, public photos, Private Album, location, Stories, album requests/access, likes/interactions, notifications, blocks, and other account-bound data. The actual scope needs a formal backend design based on the Production schema, foreign keys, and safety needs.', 'Chat can involve multiple users, so the client must not guess deletion. Humans must approve the strategy before backend implementation, such as sender-content removal, de-identification while preserving conversation integrity, or necessary retention for safety, reports, and law. This Policy does not pretend an unfinished technical policy is decided.'] },
    { heading: '5. Retention and successful deletion', paragraphs: ['When necessary, limited data may be retained to prevent fraud/abuse, protect account/platform safety, meet legal obligations or lawful authority requests, resolve disputes, or protect users and third parties. Data without a retention need should be removed or appropriately de-identified.', 'After a formal deletion succeeds, the account should no longer sign in in its original state, the profile should stop appearing as active, and approved-scope data should be removed or de-identified. Limited lawful/safety retention follows the Privacy Policy and applicable law.'] },
    { heading: '6. Current label and release gates', paragraphs: ['Permanent account deletion has not completed its safe backend process and will be provided before official release. The UI must not say “Your account has been permanently deleted” unless the backend completed every required operation.'], bullets: ['Release requires Production schema inventory, Auth deletion design, handling for profile/photos/Stories/Location/Notifications/Blocks/Likes, a human-approved chat/retention strategy, a secure RPC or controlled backend, and full runtime acceptance. This work is outside the Legal Center phase.'] },
  ] },
};

export function getLegalDocuments(locale: SupportedLocale): Record<LegalDocumentId, LegalDocument> {
  return locale === 'zh-TW' ? zhTW : en;
}
